.nh
.TH "TUSK" "1" "May 2026" "Tusk v1.0.0-dev" "Tusk Manual"

.SH NAME
tusk-node - Manage individual nodes (create, get, list, modify, move, delete)


.SH SYNOPSIS
\fBtusk node [flags]\fP


.SH DESCRIPTION
Manage individual nodes in the workspace.

.PP
A node is one markdown file with TOML frontmatter declaring its type and
properties. The node subcommands are thin wrappers over the same internal
service the watcher and reindex use, so creating a node by CLI and creating
one by saving a file in your editor produce identical index state.

.PP
Use "tusk node create" to author a new file, "tusk node modify" to change
frontmatter properties, "tusk node move" to atomically rename a node and
rewrite all referring edges, and "tusk node list" to query the index with
the filter grammar.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for node


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	emit debug-level logs to stderr


.SH SEE ALSO
\fBtusk(1)\fP, \fBtusk-node-create(1)\fP, \fBtusk-node-delete(1)\fP, \fBtusk-node-get(1)\fP, \fBtusk-node-list(1)\fP, \fBtusk-node-modify(1)\fP, \fBtusk-node-move(1)\fP
