.nh
.TH "TUSK" "1" "May 2026" "Tusk v1.0.0-dev" "Tusk Manual"

.SH NAME
tusk-node-delete - Delete a node file and remove it from the index


.SH SYNOPSIS
\fBtusk node delete  [flags]\fP


.SH DESCRIPTION
Delete a node file from disk and remove it from the index.

.PP
Edges pointing at the deleted node remain in the index as dangling
references; "tusk doctor" will surface them. Use "tusk node move" if you
want to rename rather than remove.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	emit debug-level logs to stderr


.SH EXAMPLE
.EX
  # Delete a stale note
  tusk node delete notes/2024-old

  # See which edges are now dangling
  tusk doctor
.EE


.SH SEE ALSO
\fBtusk-node(1)\fP
