version: "2"

linters:
  enable:
    - varnamelen
  settings:
    varnamelen:
      min-name-length: 2
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-names: []
      ignore-decls: []
  exclusions:
    rules:
      - linters: [errcheck]
        path: _test\.go
      - linters: [errcheck]
        text: 'Error return value of `.*\.Close` is not checked'
