User tinyproxy
Group tinyproxy
Port 8888
Listen 127.0.0.1
Timeout 600
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 100
Allow 127.0.0.1
ConnectPort 443
ConnectPort 80
Filter "/etc/tinyproxy/filter"
FilterDefaultDeny Yes
FilterExtended Yes
